<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-19T17:57:33 IST" name="Default suite" finished-at="2023-04-19T17:58:15 IST" duration-ms="42064">
    <groups>
    </groups>
    <test started-at="2023-04-19T17:57:33 IST" name="Default test" finished-at="2023-04-19T17:58:15 IST" duration-ms="42064">
      <class name="testCases.AddProducts">
        <test-method is-config="true" signature="beforetest()[pri:0, instance:testCases.AddProducts@8ff5094]" started-at="2023-04-19T17:57:33 IST" name="beforetest" finished-at="2023-04-19T17:57:39 IST" duration-ms="6020" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforetest -->
        <test-method signature="addprod()[pri:0, instance:testCases.AddProducts@8ff5094]" started-at="2023-04-19T17:57:39 IST" name="addprod" finished-at="2023-04-19T17:58:15 IST" duration-ms="35415" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Field Data Mismatched expected [GCID] but found [3],
Field Data Mismatched expected [2500.0] but found [2500],
Field Data Mismatched expected [3500.0] but found [3500],
Field Data Mismatched expected [3600.0] but found [3600],
Field Data Mismatched expected [centimeter] but found [2],
Field Data Mismatched expected [20.0] but found [20],
Field Data Mismatched expected [25.0] but found [25],
Field Data Mismatched expected [25.0] but found [25],
Field Data Mismatched expected [Gram] but found [2],
Field Data Mismatched expected [50.0] but found [50],
Field Data Mismatched expected [centimeter] but found [2],
Field Data Mismatched expected [20.0] but found [20],
Field Data Mismatched expected [20.0] but found [20],
Field Data Mismatched expected [20.0] but found [20],
Field Data Mismatched expected [Gram] but found [2],
Field Data Mismatched expected [50.0] but found [50]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Field Data Mismatched expected [GCID] but found [3],
Field Data Mismatched expected [2500.0] but found [2500],
Field Data Mismatched expected [3500.0] but found [3500],
Field Data Mismatched expected [3600.0] but found [3600],
Field Data Mismatched expected [centimeter] but found [2],
Field Data Mismatched expected [20.0] but found [20],
Field Data Mismatched expected [25.0] but found [25],
Field Data Mismatched expected [25.0] but found [25],
Field Data Mismatched expected [Gram] but found [2],
Field Data Mismatched expected [50.0] but found [50],
Field Data Mismatched expected [centimeter] but found [2],
Field Data Mismatched expected [20.0] but found [20],
Field Data Mismatched expected [20.0] but found [20],
Field Data Mismatched expected [20.0] but found [20],
Field Data Mismatched expected [Gram] but found [2],
Field Data Mismatched expected [50.0] but found [50]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at pages.AddProductPage.verifyProdDetails(AddProductPage.java:323)
at testCases.AddProducts.addprod(AddProducts.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addprod -->
      </class> <!-- testCases.AddProducts -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
